const assert = require('node:assert/strict');
const {normalizeSeries,smoothSeries,applyReferenceDivision} = require('../pl_mapping_static/processing.js');
assert.deepEqual(normalizeSeries([2,null,4]),[0,null,1]);
assert.deepEqual(normalizeSeries([null,null]),[null,null]);
assert.deepEqual(applyReferenceDivision([1,2,3,4],[0,2,null,1e-15],0),[null,1,null,null]);
assert.deepEqual(applyReferenceDivision([2,4],[1,3],1),[1,1]);
const x=Array.from({length:13},(_,i)=>3*i*i+2*i+1);
const y=smoothSeries(x,7,2);
y.forEach((v,i)=>assert.ok(Math.abs(v-x[i])<1e-8));
x[6]=null;assert.equal(smoothSeries(x,7,2)[6],null);
const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../pl_mapping_static/app.js'),'utf8');
const sandbox={els:{referenceOffset:{value:'0'}},normalizeSeries,smoothSeries,applyReferenceDivision};vm.createContext(sandbox);
vm.runInContext(source.slice(source.indexOf('function applyReferenceAndTraceSettings('),source.indexOf('function buildCenteredEdges(')),sandbox);
const raw=[{x:[500,510,520],y:[1,null,3]},{x:[500,510,520],y:[1,null,3]}];
const exported=sandbox.applyReferenceAndTraceSettings(raw,null,{applyOffset:false,offsetFactor:1});
assert.equal(exported[1].y[0],1);assert.equal(exported[1].y[1],null);
const displayed=sandbox.applyReferenceAndTraceSettings(raw,null,{applyOffset:true,offsetFactor:1});
assert.equal(displayed[1].y[0],3);assert.equal(displayed[1].y[1],null);
console.log('Processing regressions passed: missing values, reference masking, polynomial smoothing, export/display separation.');
